#!/bin/sh

set -e

HOST_IP=$(ip -o route get 8.8.8.8 | cut -d\  -f8)

exec nsupdate -k $KEYFILE <<END
server $DNS_SERVER
zone $DNS_ZONE
update delete $DNS_NAME A
update add $DNS_NAME $DNS_TTL A $HOST_IP
show
send
END

