#!/bin/sh

set -e

# override EXTERNAL_IP if you want to use a different
# route through your network.  Generally useful if you're
# using something like a VPN.
EXTERNAL_IP="${EXTERNAL_IP:-8.8.8.8}"
HOST_IP="${HOST_IP:-$(ip -o route get $EXTERNAL_IP | cut -d\  -f8)}"

exec nsupdate -k $KEYFILE <<END
server $DNS_SERVER
zone $DNS_ZONE
update delete $DNS_NAME A
update add $DNS_NAME $DNS_TTL A $HOST_IP
show
send
END

