#!/bin/sh

set -e

# use www.cv-library.co.uk to ensure we go through
# the VPN if the VPN is used.
HOST_IP="${HOST_IP:-$(ip -o route get 109.169.5.15 | cut -d\  -f8)}"

exec nsupdate -k $KEYFILE <<END
server $DNS_SERVER
zone $DNS_ZONE
update delete $DNS_NAME A
update add $DNS_NAME $DNS_TTL A $HOST_IP
show
send
END

